# Generated by Django 4.1.4 on 2023-01-07 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_set",
            field=models.ManyToManyField(
                related_name="account_follower_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following_set",
            field=models.ManyToManyField(
                related_name="account_following_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
